server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gripp
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  security:
    user:
      name: gripp
      password: $2a$10$LYAbcKFc65ImHQYH32mF0OJFquXIRy8m9PPJgWTJ2AOfohdPb8tja
      roles: ADMIN

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    disable-swagger-default-url: false
  cache:
    disabled: true

gripp:
  jwt:
    secret: gripp
