server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1

spring:
  datasource:
    url: jdbc:mysql://${env.GRIPP_DB_HOSTNAME}:${env.GRIPP_DB_PORT}/${env.GRIPP_DB_SCHEMA}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${env.GRIPP_DB_USERNAME}
    password: ${env.GRIPP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  rabbitmq:
    addresses: ${env.GRIPP_RABBITMQ_ADDRESS}
  security:
    user:
      name: ${env.GRIPP_ADMIN_NAME}
      password: ${env.GRIPP_ADMIN_PASSWORD}
      roles: ADMIN
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 2GB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    disable-swagger-default-url: false
    operations-sorter: alpha
    tags-sorter: alpha
    persist-authorization: true
  cache:
    disabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include:
          - env
          - health
          - httptrace
          - metrics
  endpoint:
    health:
      show-details: always

.env:
  ignoreIfMissing: false

gripp:
  jwt:
    secret: ${env.GRIPP_JWT_SECRET}
