server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gripp
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

gripp:
  jwt:
    secret: gripp-secret-gripp-secret-gripp-secret-gripp-secret-gripp-secret-gripp-secret-gripp-secret
