version: "3.1"

services:
  gripp:
    build: "gripp"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - gripp-upload:/gripp/upload
    environment:
      TZ: "Asia/Seoul"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: "unless-stopped"

volumes:
  gripp-upload:
