version: "3.1"

services:
  gripp:
    build: "gripp"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - gripp-upload:/gripp/upload
    environment:
      TZ: "Asia/Seoul"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: "unless-stopped"
  video-processor:
    build: "video-processor"
    environment:
      TZ: "Asia/Seoul"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: "unless-stopped"
  admin:
    build: "admin"
    ports:
      - "127.0.0.1:8081:80"
    environment:
      TZ: "Asia/Seoul"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: "unless-stopped"
  prometheus:
    build: "prometheus"
    ports:
      - "127.0.0.1:8082:9090"
    volumes:
      - gripp-prometheus:/prometheus
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: "unless-stopped"
  grafana:
    image: "grafana/grafana:7.5.17"
    ports:
      - "127.0.0.1:8083:3000"
    volumes:
      - gripp-grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: "${GRIPP_GRAFANA_DEFAULT_USER-:admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRIPP_GRAFANA_DEFAULT_PASSWORD-:admin}"
      GF_SERVER_DOMAIN: "${GRIPP_GRAFANA_DOMAIN:-localhost}"
      GF_SERVER_ROOT_URL: "${GRIPP_GRAFANA_ROOT_URL:-%(protocol)s://%(domain)s:%(http_port)s/grafana/}"
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_AUTH_BASIC_ENABLED: false
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    restart: "unless-stopped"

volumes:
  gripp-upload:
  gripp-prometheus:
  gripp-grafana:
