scrape_configs:
  - job_name: gripp
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    basic_auth:
      username: "${GRIPP_ADMIN_NAME}"
      password: "${GRIPP_ADMIN_PASSWORD_RAW}"
    static_configs:
      - targets: ["${GRIPP_PROMETHEUS_TARGET}"]
