name: deploy

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy.yml
      - gripp/**
      - video-processor/**
      - admin/**
      - prometheus/**
      - docker-compose.yml

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_GRIPP_ADMIN_NAME: ${{ format('''{0}''', secrets.GRIPP_ADMIN_NAME) }}
          envkey_GRIPP_ADMIN_PASSWORD: ${{ format('''{0}''', secrets.GRIPP_ADMIN_PASSWORD) }}
          envkey_GRIPP_ADMIN_PASSWORD_RAW: ${{ format('''{0}''', secrets.GRIPP_ADMIN_PASSWORD_RAW) }}
          envkey_GRIPP_AWS_ACCESS_KEY: ${{ format('''{0}''', secrets.GRIPP_AWS_ACCESS_KEY) }}
          envkey_GRIPP_AWS_SECRET_KEY: ${{ format('''{0}''', secrets.GRIPP_AWS_SECRET_KEY) }}
          envkey_GRIPP_AWS_REGION: ${{ format('''{0}''', secrets.GRIPP_AWS_REGION) }}
          envkey_GRIPP_AWS_S3_ENDPOINT: ${{ format('''{0}''', secrets.GRIPP_AWS_S3_ENDPOINT) }}
          envkey_GRIPP_AWS_S3_BUCKET: ${{ format('''{0}''', secrets.GRIPP_AWS_S3_BUCKET) }}
          envkey_GRIPP_DB_HOSTNAME: ${{ format('''{0}''', secrets.GRIPP_DB_HOSTNAME) }}
          envkey_GRIPP_DB_PORT: ${{ format('''{0}''', secrets.GRIPP_DB_PORT) }}
          envkey_GRIPP_DB_SCHEMA: ${{ format('''{0}''', secrets.GRIPP_DB_SCHEMA) }}
          envkey_GRIPP_DB_USERNAME: ${{ format('''{0}''', secrets.GRIPP_DB_USERNAME) }}
          envkey_GRIPP_DB_PASSWORD: ${{ format('''{0}''', secrets.GRIPP_DB_PASSWORD) }}
          envkey_GRIPP_RABBITMQ_ADDRESS: ${{ format('''{0}''', secrets.GRIPP_RABBITMQ_ADDRESS) }}
          envkey_GRIPP_JWT_SECRET: ${{ format('''{0}''', secrets.GRIPP_JWT_SECRET) }}
          envkey_GRIPP_MAIN_API_ENDPOINT: ${{ format('''{0}''', secrets.GRIPP_MAIN_API_ENDPOINT) }}
          envkey_GRIPP_DEEP_API_ENDPOINT: ${{ format('''{0}''', secrets.GRIPP_DEEP_API_ENDPOINT) }}
          envkey_GRIPP_DEEP_TOKEN: ${{ format('''{0}''', secrets.GRIPP_DEEP_TOKEN) }}
          envkey_GRIPP_PROMETHEUS_TARGET: ${{ format('''{0}''', secrets.GRIPP_PROMETHEUS_TARGET) }}
          envkey_GRIPP_GRAFANA_DOMAIN: ${{ format('''{0}''', secrets.GRIPP_GRAFANA_DOMAIN) }}
          envkey_GRIPP_GRAFANA_ROOT_URL: ${{ format('''{0}''', secrets.GRIPP_GRAFANA_ROOT_URL) }}
          envkey_GRIPP_GRAFANA_DEFAULT_USER: ${{ format('''{0}''', secrets.GRIPP_GRAFANA_DEFAULT_USER) }}
          envkey_GRIPP_GRAFANA_DEFAULT_PASSWORD: ${{ format('''{0}''', secrets.GRIPP_GRAFANA_DEFAULT_PASSWORD) }}
          file_name: .env
          fail_on_empty: true
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_SSH_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_SSH_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          ARGS: -avz --delete
          TARGET: gripp-backend/
          EXCLUDE: .config, .git, .github
      - name: Build Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: |
            cd ~/gripp-backend
            docker compose up -d --build
            docker image prune -f
