name: test

on:
  pull_request:
    branches:
      - "**"
    paths:
      - .github/workflows/test.yml
      - gripp/**

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: gripp
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: gripp/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
